### ISSUE TITLE
Definition of function version-valid-p is absent

### ISSUE THREAD

**Issue by svetlyak40wt** [cldm/cl-semver#1]
When I do `(cl-semver:read-version-from-string "0.1.0")`, this error happens:

```
The function CL-SEMVER:VERSION-VALID-P is undefined.
   [Condition of type UNDEFINED-FUNCTION]

Restarts:
 0: [RETRY] Retry SLIME REPL evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {1002CF0003}>)

Backtrace:
  0: ("undefined function")
  1: (CL-SEMVER:READ-VERSION-FROM-STRING "0.1.0" #<unused argument>)
```

### Workaround
```
(cl-semver::parse 'cl-semver::version "0.1.0")
```

### Possible solution

Probably, `version-valid-p` was replaced with `versionp`?

**Comment by mmontone** [comment]
git pull and use version-string-valid-p instead.

I'm not maintaining this library and some of the test fail (some of the comparison tests)

**Comment by mmontone** [comment]
```
TEST> (cl-semver:read-version-from-string "0.1.0")
#v"0.1.0"
NIL
T
```

**Comment by svetlyak40wt** [comment]
Thank you, @mmontone!

@mmontone by the way, what is the future of the CLDM project? Did you abandon it? And if yes, then what is the reason?

**Comment by mmontone** [comment]
Yes. I've kind of abandoned it. Because of some design/architecture decisions didn't turn out fine in the end. It aimed to be a very distributed library manager, but I found that it suffered from some difficulties because of not working with some central repository (or N central repositories). I would have to rewrite it to work more similar to what other package managers work like NPM, Ruby Bundler, etc. Also, people seem to be happy enough with Quicklisp, although it has limitations.

**Comment by svetlyak40wt** [comment]
Thank you for explanations. Indeed, quicklisp + qlot solve most tasks.
